### ISSUE TITLE
Run failed: CodeQL (NETSDK1045)

### ISSUE THREAD

**Issue by lipchev** [angularsen/UnitsNet#1538]
I've been getting emails (which I've been ignoring so far) about the "Run failed: CodeQL": [link](https://github.com/lipchev/UnitsNet/actions/runs/14410646119/job/40417493473).

Here's relevant output:

>   error NETSDK1045: The current .NET SDK does not support targeting .NET 9.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 9.0.

I'm not sure if [this part](https://github.com/angularsen/UnitsNet/blob/47435c0d8d725337e52061e568795425dea32c8f/.github/workflows/codeql-analysis.yml#L43) of the `.yml` was kept intentionally like so:
    
``` yaml
    # .NET 6 is used in CodeGen project.
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
```
